version: '3.0'
services:
  postgres:
    image: postgres:14.5
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=downloadslinks
    ports:
      - '5678:5432'
    volumes:
      - mobtakerandb:/var/lib/postgresql/data

  redis:
    image: 'redis:latest'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - '4567:6379'
volumes:
  mobtakerandb:
    driver: local
